# Generated by Django 5.1.1 on 2024-11-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModulesManager', '0002_modules_isenabled_modules_prix_usermodule_cout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='options',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
