# Generated by Django 5.1.1 on 2024-11-14 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_evenement_numero_uuid'),
        ('ModulesManager', '0003_modules_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermodule',
            unique_together={('user', 'module')},
        ),
        migrations.CreateModel(
            name='EventModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(blank=True, default=None, null=True)),
                ('cout', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.evenement')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModulesManager.modules')),
            ],
            options={
                'unique_together': {('event', 'module')},
            },
        ),
    ]
