# Generated by Django 5.1.1 on 2024-10-01 00:48

import ContentSharing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0003_evenement_numero_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(upload_to=ContentSharing.models.CodeQR.get_upload_path)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_qr', to='Event.evenement')),
            ],
            options={
                'verbose_name': 'Code QR',
                'verbose_name_plural': 'Codes QR',
            },
        ),
        migrations.CreateModel(
            name='ContenuGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo')], max_length=5)),
                ('fichier', models.FileField(upload_to=ContentSharing.models.ContenuGalerie.get_upload_path)),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='Event.evenement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenu de galerie',
                'verbose_name_plural': 'Contenus de galerie',
            },
        ),
    ]
