# Generated by Django 5.1.1 on 2024-10-01 01:58

import ContentSharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentSharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeqr',
            name='code',
            field=models.CharField(default=ContentSharing.models.CodeQR.generate_unique_code, max_length=100, unique=True),
        ),
    ]
