# Generated by Django 5.1.1 on 2024-10-01 02:00

import ContentSharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentSharing', '0002_alter_codeqr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeqr',
            name='img',
            field=models.ImageField(blank=True, upload_to=ContentSharing.models.CodeQR.get_upload_path),
        ),
    ]
